### PR TITLE
Added whitelist_classes functionality in order to be able to whitelist your own classes

### PR DESCRIPTION
**Pull request by Akhilesh05**
I was having problem to store Regexp in the .yml
After doing this dev, I was able to add the Regexp class to the whitelisted classes
Hence easily and practically save Regexp in the .yml

### CODE REVIEW

**Comment by paladiy** [comment]
@Akhilesh05 thank you for the contribution. 
I'm almost ready to merge PR, just one small thing, could you update readme with the new functionality?

**Comment by le0pard** [comment]
Looks good. How about name `yaml_whitelist_classes` instead `whitelist_classes`, so it will be more clear about this classes usage?

**Comment by Akhilesh05** [comment]
@paladiy Sure, I'll update the readme ASAP
@le0pard Yes, `yaml_whitelist_classes` seems fine, shall I proceed with it?

**Comment by paladiy** [comment]
@Akhilesh05 yes, let’s do name suggested by @le0pard

**Comment by le0pard** [comment]
Looks good. Waiting for @paladiy

**Comment by Akhilesh05** [comment]
@paladiy Done!
I hope the information I added in the readme is good.

**Comment by paladiy** [comment]
@Akhilesh05 merged and released new version [1.1.0](https://rubygems.org/gems/global/versions/1.1.0)

Thank you for contribution 👍

**Pull request merged**
